name: Publish
permissions:
  id-token: write
  pages: write

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.3.2"
      - name: Install package
        run: poetry install

      - name: Pull repos
        id: pull
        run: poetry run python -m uc_python.pull
      - name: Build slides
        id: build
        run: poetry run python -m uc_python.build
      - name: Create site
        id: collate
        run: poetry run python -m uc_python.collate
      - name: Upload artifact
        id: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

